#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(CoopArena_Ability_Attack);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CoopArena_Cooldown_Attack);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(CoopArena_Ability_Dash);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CoopArena_Cooldown_Dash);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(CoopArena_Event_Attack);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(CoopArena_Status_Dead);
